---
apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZHgzdnlqaTRv
  CLOUDINARY_KEY: NTk1OTU4OTcxODM0NzU3
  CLOUDINARY_SECRET: N3ZSRnhfbF9YNllsc3pZMVFCaHNxTjJrQllB
  MAPBOX_TOKEN: cGsuZXlKMUlqb2ljMkYxY21GMmEyRnlhMmtpTENKaElqb2lZMjAzTmpGb01HTnJNR3RzZVRKcGNYaHphakJ2WTJaNE15SjkuRjR3VzcxSFJfbGNfUDR4RFd0YnlEQQ==
  DB_URL: bW9uZ29kYitzcnY6Ly9zYXVyYXZrYXJraXRlY2g6MHRBQ0lTTDNReVpCZHZmUkBzYXVyYXYtZGItdGhyZWV0aWVyLnRibmx0Lm1vbmdvZGIubmV0Lz9yZXRyeVdyaXRlcz10cnVlJnc9bWFqb3JpdHkmYXBwTmFtZT1zYXVyYXYtZGItdGhyZWV0aWVy
  SECRET: c2F1cmF2a2Fya2k=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yelp-camp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yelp-camp
  template:
    metadata:
      labels:
        app: yelp-camp
    spec:
      containers:
        - name: yelp-camp-container
          image: sauravkarki/campapp:latest
          ports:
            - containerPort: 3000
          env:
            - name: CLOUDINARY_CLOUD_NAME
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_CLOUD_NAME
            - name: CLOUDINARY_KEY
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_KEY
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: CLOUDINARY_SECRET
            - name: MAPBOX_TOKEN
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: MAPBOX_TOKEN
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: DB_URL
            - name: SECRET
              valueFrom:
                secretKeyRef:
                  name: yelp-camp-secrets
                  key: SECRET
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30   # Adjust the initial delay here

---
apiVersion: v1
kind: Service
metadata:
  name: yelp-camp-service
spec:
  selector:
    app: yelp-camp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
